#!/bin/sh
### BEGIN INIT INFO
# Provides:       pow
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   1
# Description:    POW Rack server (iptables conf).
### END INIT INFO

set +e   # Don't exit on error status

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/pow
NAME=pow
DESC="POW Rack server (iptables conf)."
HTTP_PORT=20559

case "$1" in
  start)
    if [ `iptables -t nat -L | grep $HTTP_PORT | wc -l` -eq 0 ] ; then
      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports $HTTP_PORT
    fi
    ;;
  stop)
    RULE_NUM=`iptables -t nat -L --line-numbers | grep $HTTP_PORT | awk -F " " '{ print $1 }'`
    iptables -t nat -D OUTPUT $RULE_NUM
    ;;
  restart)
    $0 stop
    $0 start
    ;;
esac

