#!/bin/sh
### BEGIN INIT INFO
# Provides:       pow
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   1
# Description:    POW Rack server (iptables configuration).
### END INIT INFO

set +e   # Don't exit on error status

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/pow
NAME=pow
DESC="POW Rack server (iptables configuration)."
HTTP_PORT=20559

case "$1" in
  start)
    if [ `iptables -t nat -L | grep $HTTP_PORT | wc -l` -eq 0 ] ; then
      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports $HTTP_PORT
      #iptables -t nat -A OUTPUT -p tcp -d 10.0.2.2  --dport 80 -j REDIRECT --to-ports $HTTP_PORT
    fi
    ;;
  stop)
    RULE_NUMS=`iptables -t nat -L --line-numbers -n | grep $HTTP_PORT | awk '{a[i++]=$0} END { for (j=i-1; j>=0;) print a[j--] }' | awk -F " " '{ print $1 }'`
    for RULE_NUM in $RULE_NUMS ; do
      iptables -t nat -D OUTPUT $RULE_NUM
    done
    ;;
  restart)
    $0 stop
    $0 start
    ;;
esac

